services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - front_back

  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    # ports:
    #   - "8000:8000"
    networks:
      - front_back
      - back_redis

  redis:
    image: redis:latest
    container_name: redis-server
    networks:
      - back_redis
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--save", "", "--appendonly", "no"]

networks:
  front_back:
    driver: bridge
  back_redis:
    driver: bridge
