services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - quiminhoca-network

  fast-api:
    build:
      context: ./fast-api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ".env"
    ports:
      - "8000:8000"
    networks:
      - quiminhoca-network
    depends_on:
      - redis
      - mariadb

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - quiminhoca-network
    volumes:
      - quiminhoca-mariadb:/var/lib/mysql

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - quiminhoca-network
    volumes:
      - quiminhoca-redis:/data
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  quiminhoca-mariadb:
  quiminhoca-redis:

networks:
  quiminhoca-network:
    driver: bridge
