services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
      args:
        VITE_FRONTEND_BASE_URL: ${VITE_FRONTEND_BASE_URL:-/quiminhoca/}
        VITE_API_URL: ${VITE_API_URL:-localhost/api}

    restart: unless-stopped
    environment:
      NODE_ENV: production
      VITE_FRONTEND_BASE_URL: ${VITE_FRONTEND_BASE_URL:-/quiminhoca/}
      VITE_API_URL: ${VITE_API_URL:-localhost/api}
    ports:
      - "${FRONTEND_HTTP_PORT:-80}:80"
    networks:
      - quiminhoca-network

  fast-api:
    build:
      context: ./fast-api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ".env"
    networks:
      - quiminhoca-network
    depends_on:
      - redis
      - mariadb

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_USER: ${MARIADB_USER:-quiminhoca}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-changeme}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-changeme}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-quiminhoca_db}
    networks:
      - quiminhoca-network
    volumes:
      - quiminhoca-mariadb:/var/lib/mysql

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - quiminhoca-network
    volumes:
      - quiminhoca-redis:/data
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  quiminhoca-mariadb:
  quiminhoca-redis:

networks:
  quiminhoca-network:
    driver: bridge
